name: Social-Media-Api-CI-Workflow

on: 
   pull_request:
      branches:
        - main
   push:
      branches:
         - main

jobs: 

   test:
       name: 'Run unit tests'
       runs-on: ubuntu-22.04
       steps:
         - uses: actions/checkout@v4
         - name: Use Node.js
           uses: actions/setup-node@v4
           with:
             node-version: '20.x'
         - name: Install dependencies
           run: npm install
         - name: Run eslint
           run: npm run eslint
         - name: 'Start the server'
           run: echo "Yeah we are done with this!!"
           env:
             DOTENV_KEY: ${{ secrets.DOTENV_KEY }}

   
